// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rcrud.Server;

#nullable disable

namespace Rcrud.Server.Migrations
{
    [DbContext(typeof(Db))]
    partial class DbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Rcrud.Shared.Osoba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Godiste")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Osobas");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Godiste = 83,
                            Name = "Pera",
                            Surname = "Peric"
                        },
                        new
                        {
                            Id = -2,
                            Godiste = 35,
                            Name = "Neko",
                            Surname = "Nekic"
                        },
                        new
                        {
                            Id = -3,
                            Godiste = 345,
                            Name = "Trecko",
                            Surname = "Treckovic"
                        },
                        new
                        {
                            Id = -4,
                            Godiste = 83,
                            Name = "Asd",
                            Surname = "Qwe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
